<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;

class BelieverImportTemplateExport implements FromArray
{
    public function array(): array
    {
        return [
            [
                'lastname',
                'firstname',
                'gender',
                'marital_status',
                'birth_date',
                'birth_place',
                'ethnicity',
                'nationality',
                'number_of_children',
                'cni_number',
                'whatsapp_number',
                'phone_number',
                'email',
                'commune',
                'quartier',
                'sous_quartier',
                'connaissance_eglise',
                'original_church',
                'arrival_year',
                'conversion_date',
                'conversion_place',
                'baptised',
                'baptism_date',
                'baptism_place',
                'baptism_pastor',
                'baptism_card_number',
                'membership_card_number',
                'level_of_education',
                'degree',
                'qualification',
                'fonction',
                'company',
                'professional_contact',
                'responsibility_old',
                'responsibility_current',
                'responsibility_desired',
                'languages',
            ],
            [
                'Kouassi',
                'Jean',
                'Masculin',
                'Célibataire',
                '1998-05-14',
                'Bouaké',
                'Baoulé',
                'Ivoirienne',
                '0',
                'CI123456789',
                '0707070707',
                '0101010101',
                'jean@example.com',
                'Yopougon',
                'Niangon',
                'Sicogi',
                'Invité par un ami',
                'Église Baptiste de Bouaké',
                '2023',
                '2018-06-10',
                'Bouaké',
                'Oui',
                '2019-08-20',
                'Yopougon',
                'Pasteur Yao',
                'BAP-2023-001',
                'AEBECI-2023-015',
                'Licence',
                'Licence Informatique',
                'Développeur Web',
                'Développeur',
                'Tech CI',
                '0505050505',
                'Choriste',
                'Moniteur',
                'Ancien',
                'Français|1|1;Baoulé|1|0;Anglais|0|1',
            ],
        ];
    }
}